import { test } from '@e2e-dev/web';
import { expect } from 'e2e';

// The server script seeds real upstream Dashy with deterministic configuration.
// DASHY_URL must point to an equivalent disposable instance: this suite saves config.
test('Dashy dashboard, live search, tile navigation and header navigation', async ({ app, screen, browser }) => {
  await app.open('/');
  await expect(screen.getByRole('heading', 'HAOS Dashy E2E')).toBeVisible();
  const configTile = screen.getByRole('link', /^Configuration file/);
  const healthTile = screen.getByRole('link', /^Dashy health/);
  await expect(configTile).toBeVisible();
  await expect(healthTile).toBeVisible();
  const search = screen.getByRole('searchbox');
  await search.fill('Configuration');
  await expect(configTile).toBeVisible();
  await expect(healthTile).toHaveCount(0);
  await search.fill('does-not-exist-e2e');
  await expect(configTile).toHaveCount(0);
  await expect(healthTile).toHaveCount(0);
  await search.press('Escape');
  await expect(search).toHaveValue('');
  await expect(healthTile).toBeVisible();
  const healthResponse = browser.waitForResponse(/\/healthz$/);
  await healthTile.tap();
  expect((await healthResponse).status).toBe(200);
  await expect(browser).toHaveURL(/\/healthz$/);
  await expect(screen.getByText(/"status"\s*:\s*"ok"/)).toBeVisible();
  await browser.back();
  await expect(configTile).toBeVisible();
  await configTile.tap();
  await expect(browser).toHaveURL(/\/conf.yml$/);
  await expect(screen.getByText(/title: HAOS Dashy E2E/)).toBeVisible();
  await browser.back();
  await expect(screen.getByRole('heading', 'HAOS Dashy E2E')).toBeVisible();
  await screen.getByRole('link', 'Config source', { exact: true }).tap();
  await expect(browser).toHaveURL(/\/conf.yml$/);
  await expect(screen.getByText(/title: HAOS Dashy E2E/)).toBeVisible();
});

test('Dashy theme selection changes rendered theme and persists after reload', async ({ app, screen, browser }) => {
  await app.open('/');
  await expect(screen.getByRole('heading', 'HAOS Dashy E2E')).toBeVisible();
  await expect(browser.locator('html')).toHaveAttribute('data-theme', 'colorful');
  await screen.getByRole('button', 'Options', { exact: true }).tap();
  await browser.locator('.theme-dropdown input').tap();
  await screen.getByRole('option', 'dracula', { exact: true }).tap();
  await expect(browser.locator('html')).toHaveAttribute('data-theme', 'dracula');
  expect(await browser.evaluate(() => localStorage.getItem('theme'))).toBe('dracula');
  await browser.reload();
  await expect(screen.getByRole('heading', 'HAOS Dashy E2E')).toBeVisible();
  await expect(browser.locator('html')).toHaveAttribute('data-theme', 'dracula');
});

test('Dashy layout and item size persist; minimal view and missing route recover', async ({ app, screen, browser }) => {
  await app.open('/');
  await screen.getByRole('button', 'Options', { exact: true }).tap();
  // Upstream layout/size icons do not expose accessible button names.
  const vertical = browser.locator('.grid-2 > div:first-child .layout-icon:nth-child(3)');
  const large = browser.locator('.grid-2 > div:last-child .layout-icon:nth-child(3)');
  await vertical.tap();
  await expect(vertical).toHaveAttribute('class', /selected/);
  await large.tap();
  await expect(large).toHaveAttribute('class', /selected/);
  await browser.reload();
  await screen.getByRole('button', 'Options', { exact: true }).tap();
  await expect(vertical).toHaveAttribute('class', /selected/);
  await expect(large).toHaveAttribute('class', /selected/);
  await screen.getByRole('link', 'Minimal', { exact: true }).tap();
  await expect(browser).toHaveURL(/\/minimal$/);
  await expect(screen.getByRole('link', /^Configuration file/)).toBeVisible();
  await screen.getByRole('searchbox').fill('Configuration');
  await expect(screen.getByRole('link', /^Dashy health/)).toHaveCount(0);
  await screen.getByRole('searchbox').press('Escape');
  await expect(screen.getByRole('link', /^Dashy health/)).toBeVisible();
  await app.open('/missing-e2e-route');
  await expect(screen.getByRole('heading', '404', { exact: true })).toBeVisible();
  await screen.getByRole('link', 'Back Home', { exact: true }).tap();
  await expect(screen.getByRole('heading', 'HAOS Dashy E2E')).toBeVisible();
  await expect(screen.getByRole('link', /^Configuration file/)).toBeVisible();
});

test('Dashy interactive editor creates, updates and deletes items, sections and local widgets', async ({ app, screen, browser }) => {
  await app.open('/');
  await screen.getByRole('button', 'Options', { exact: true }).tap();
  await screen.getByRole('button', 'Edit Mode', { exact: true }).tap();
  await expect(screen.getByText('You are in Edit Mode').first()).toBeVisible();
  await browser.locator('.add-new-item').tap();
  await expect(screen.getByRole('heading', 'Edit Item', { exact: true })).toBeVisible();
  const itemTitle = browser.locator('.edit-item .row:has-text("Item Text") input');
  const itemUrl = browser.locator('.edit-item .row:has-text("Service URL") input');
  await itemTitle.fill('Created E2E tile');
  await itemUrl.fill('/healthz');
  await browser.locator('.edit-item').getByRole('button', 'Save', { exact: true }).tap();
  const created = screen.getByRole('link', /^Created E2E tile/);
  await expect(created).toBeVisible();
  await created.tap();
  await itemTitle.fill('Updated E2E tile');
  await browser.locator('.edit-item').getByRole('button', 'Save', { exact: true }).tap();
  const updated = screen.getByRole('link', /^Updated E2E tile/);
  await expect(updated).toBeVisible();
  await expect(created).toHaveCount(0);

  await browser.locator('.add-new-section').tap();
  await expect(screen.getByRole('heading', 'Add New Section', { exact: true })).toBeVisible();
  await screen.getByRole('textbox', /^Section Name/).fill('Created E2E section');
  await browser.locator('.edit-section').getByRole('button', 'Save', { exact: true }).tap();
  const section = browser.locator('.collapsable').filter({ hasText: 'Created E2E section' });
  await expect(section.getByRole('heading', 'Created E2E section', { exact: true })).toBeVisible();
  await browser.locator('.collapsable:has-text("Created E2E section") .section-header .header-action').nth(1).tap();
  await screen.getByRole('textbox', /^Section Name/).fill('Updated E2E section');
  await browser.locator('.edit-section').getByRole('button', 'Save', { exact: true }).tap();
  await expect(screen.getByRole('heading', 'Updated E2E section', { exact: true })).toBeVisible();

  await browser.locator('.add-widget-launcher').first().tap();
  await expect(screen.getByRole('heading', 'Add New Widget', { exact: true })).toBeVisible();
  await browser.locator('.edit-widget input[type="text"]').nth(0).fill('clock');
  await browser.locator('.edit-widget input[type="text"]').nth(1).fill('Local E2E clock');
  await browser.locator('.edit-widget .add-field-tag').tap();
  await browser.locator('.edit-widget .option-row input').nth(0).fill('timeZone');
  await browser.locator('.edit-widget .option-row input').nth(1).fill('Europe/Zurich');
  await browser.locator('.edit-widget').getByRole('button', 'Save', { exact: true }).tap();
  await expect(screen.getByText('Local E2E clock', { exact: true })).toBeVisible();
  await expect(browser.locator('.clock .time')).toHaveText(/\d{1,2}:\d{2}/);
  await browser.locator('.widget-base .edit-btn').tap();
  await browser.locator('.edit-widget input[type="text"]').nth(1).fill('Updated E2E clock');
  await browser.locator('.edit-widget').getByRole('button', 'Save', { exact: true }).tap();
  await expect(screen.getByText('Updated E2E clock', { exact: true })).toBeVisible();

  const saved = browser.waitForResponse(/\/config-manager\/save$/);
  await screen.getByRole('button', 'Save to Disk', { exact: true }).tap();
  expect((await saved).status).toBe(200);
  const persisted = await browser.evaluate(async () => (await fetch('/conf.yml', { cache: 'no-store' })).text());
  expect(persisted).toContain('Updated E2E tile');
  expect(persisted).toContain('Updated E2E section');
  expect(persisted).toContain('Updated E2E clock');
  await browser.evaluate(() => { localStorage.clear(); sessionStorage.clear(); return null; });
  await browser.reload();
  await expect(screen.getByRole('link', /^Updated E2E tile/)).toBeVisible();
  await expect(screen.getByRole('heading', 'Updated E2E section', { exact: true })).toBeVisible();
  await expect(screen.getByText('Updated E2E clock', { exact: true })).toBeVisible();
  await screen.getByRole('button', 'Options', { exact: true }).tap();
  await screen.getByRole('button', 'Edit Mode', { exact: true }).tap();
  await screen.getByRole('link', /^Updated E2E tile/).secondaryTap();
  await browser.locator('.context-menu').getByText('Remove', { exact: true }).tap();
  await expect(screen.getByRole('link', /^Updated E2E tile/)).toHaveCount(0);
  await browser.locator('.collapsable:has-text("Updated E2E section") .section-header .header-action').last().tap();
  await browser.locator('.context-menu').getByText('Remove', { exact: true }).tap();
  await browser.locator('dialog[open]').getByRole('button', 'Confirm', { exact: true }).tap();
  await expect(screen.getByRole('heading', 'Updated E2E section', { exact: true })).toHaveCount(0);
  await browser.locator('.widget-base .remove-btn').tap();
  await browser.locator('dialog[open]').getByRole('button', 'Confirm', { exact: true }).tap();
  await expect(screen.getByText('Updated E2E clock', { exact: true })).toHaveCount(0);
  const cleaned = browser.waitForResponse(/\/config-manager\/save$/);
  await screen.getByRole('button', 'Save to Disk', { exact: true }).tap();
  expect((await cleaned).status).toBe(200);
  const deleted = await browser.evaluate(async () => (await fetch('/conf.yml', { cache: 'no-store' })).text());
  expect(deleted).not.toContain('Updated E2E tile');
  expect(deleted).not.toContain('Updated E2E section');
  expect(deleted).not.toContain('Updated E2E clock');
  await browser.evaluate(() => { localStorage.clear(); sessionStorage.clear(); return null; });
  await browser.reload();
  await expect(screen.getByRole('link', /^Configuration file/)).toBeVisible();
  await expect(screen.getByRole('link', /^Updated E2E tile/)).toHaveCount(0);
  await expect(screen.getByRole('heading', 'Updated E2E section', { exact: true })).toHaveCount(0);
  await expect(screen.getByText('Updated E2E clock', { exact: true })).toHaveCount(0);
});

test('Dashy YAML editor saves to disk and fresh browser state reads persisted config', async ({ app, screen, browser }) => {
  await app.open('/');
  await expect(screen.getByRole('heading', 'HAOS Dashy E2E')).toBeVisible();
  const original = await browser.evaluate(async () => (await fetch('/conf.yml', { cache: 'no-store' })).text());
  await screen.getByRole('button', 'Options', { exact: true }).tap();
  await screen.getByRole('button', 'Config', { exact: true }).tap();
  await expect(screen.getByRole('heading', 'Configuration Options')).toBeVisible();
  await screen.getByRole('button', 'Edit Config', { exact: true }).tap();
  const editor = browser.locator('.cm-content[contenteditable="true"]');
  await expect(editor).toBeVisible();
  const changed = original.replace('title: HAOS Dashy E2E', 'title: HAOS Dashy Saved E2E');
  expect(changed).not.toBe(original);
  await editor.fill(changed);
  const saved = browser.waitForResponse(/\/config-manager\/save$/);
  await screen.getByRole('button', 'Save to Disk', { exact: true }).tap();
  const response = await saved;
  expect(response.status).toBe(200);
  expect((await response.json<{ success: boolean }>()).success).toBe(true);
  await expect(screen.getByText('Config file written to disk successfully')).toBeVisible();
  await browser.keyboard.press('Escape');
  await expect(screen.getByRole('heading', 'HAOS Dashy Saved E2E')).toBeVisible();
  // Verify the server response, then discard all browser overrides before boot.
  expect(await browser.evaluate(async () => (await fetch('/conf.yml', { cache: 'no-store' })).text())).toContain('title: HAOS Dashy Saved E2E');
  await browser.evaluate(() => { localStorage.clear(); sessionStorage.clear(); return null; });
  await browser.reload();
  await expect(screen.getByRole('heading', 'HAOS Dashy Saved E2E')).toBeVisible();
  await expect(screen.getByRole('link', /^Configuration file/)).toBeVisible();
});
