#!/bin/bash

set -e
set -o pipefail

SUPERVISOR_URL="http://supervisor"
OUTPUT_FILE="${HOME}/AGENTS.md"
FULL_MODE=false

while [ "$#" -gt 0 ]; do
    case "$1" in
        --full)
            FULL_MODE=true
            shift
            ;;
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --help)
            echo "Usage: ha-context [--full] [--output FILE]"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

api_call() {
    local endpoint="$1"
    curl -s -m 10 \
        -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
        -H "Content-Type: application/json" \
        "${SUPERVISOR_URL}/${endpoint}" 2>/dev/null
}

ha_api_call() {
    local endpoint="$1"
    api_call "core/api/${endpoint}"
}

check_prerequisites() {
    if [ -z "${SUPERVISOR_TOKEN:-}" ]; then
        echo "Error: SUPERVISOR_TOKEN not set. This script must run inside a Home Assistant app." >&2
        exit 1
    fi

    for cmd in curl jq; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            echo "Error: '$cmd' is required but not installed." >&2
            exit 1
        fi
    done
}

section_system_info() {
    local core_info host_info ha_config
    core_info=$(api_call "core/info")
    host_info=$(api_call "host/info")
    ha_config=$(ha_api_call "config")

    local ha_version machine ha_os hostname timezone location_name
    ha_version=$(echo "$core_info" | jq -r '.data.version // empty' 2>/dev/null)
    machine=$(echo "$core_info" | jq -r '.data.machine // empty' 2>/dev/null)
    ha_os=$(echo "$host_info" | jq -r '.data.operating_system // empty' 2>/dev/null)
    hostname=$(echo "$host_info" | jq -r '.data.hostname // empty' 2>/dev/null)
    timezone=$(echo "$ha_config" | jq -r '.time_zone // empty' 2>/dev/null)
    location_name=$(echo "$ha_config" | jq -r '.location_name // empty' 2>/dev/null)

    if [ -z "$ha_version" ]; then
        echo "Unable to retrieve system information."
        return
    fi

    echo "- Home Assistant: ${ha_version}"
    [ -n "$machine" ] && echo "- Machine: ${machine}"
    [ -n "$ha_os" ] && echo "- OS: ${ha_os}"
    [ -n "$hostname" ] && echo "- Hostname: ${hostname}"
    [ -n "$location_name" ] && echo "- Location: ${location_name}"
    [ -n "$timezone" ] && echo "- Timezone: ${timezone}"
}

section_entity_summary() {
    local states total summary
    states=$(ha_api_call "states")

    if [ -z "$states" ] || ! echo "$states" | jq -e '.' >/dev/null 2>&1; then
        echo "Unable to retrieve entity states."
        return
    fi

    total=$(echo "$states" | jq 'length')
    summary=$(echo "$states" | jq -r '
        [.[].entity_id | split(".")[0]] | group_by(.) |
        map({domain: .[0], count: length}) |
        sort_by(-.count) |
        .[] | "| \(.domain) | \(.count) |"
    ' 2>/dev/null)

    if [ -z "$summary" ]; then
        echo "0 entities found."
        return
    fi

    echo "| Domain | Count |"
    echo "| --- | ---: |"
    echo "$summary"
    echo ""
    echo "Total: ${total} entities"

    if [ "$FULL_MODE" = true ]; then
        echo ""
        echo "### Entity Details"
        echo ""
        echo "$states" | jq -r '
            group_by(.entity_id | split(".")[0])[] |
            (.[0].entity_id | split(".")[0]) as $domain |
            "#### \($domain)\n" +
            (.[0:20] | map("- `" + .entity_id + "`") | join("\n")) +
            (if length > 20 then "\n- ...and \((length - 20)) more" else "" end) +
            "\n"
        ' 2>/dev/null
    fi
}

section_apps() {
    local apps_data
    apps_data=$(api_call "addons")

    if [ -z "$apps_data" ] || ! echo "$apps_data" | jq -e '.data.addons' >/dev/null 2>&1; then
        echo "Unable to retrieve app information."
        return
    fi

    echo "$apps_data" | jq -r '
        .data.addons[] |
        select((.installed // true) == true) |
        "- \(.name) v\(.version // "unknown") (\(.state // "unknown"))"
    ' 2>/dev/null | sort
}

section_recent_errors() {
    local error_log
    error_log=$(ha_api_call "error_log")

    if [ -z "$error_log" ] || [ "$error_log" = "\"\"" ]; then
        echo "No recent errors."
        return
    fi

    echo '```text'
    echo "$error_log" | tail -20 | cut -c1-200
    echo '```'
}

generate_agents_md() {
    local timestamp tmp_file
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    tmp_file=$(mktemp "${OUTPUT_FILE}.XXXXXX")

    cat > "$tmp_file" << HEADER
# Home Assistant Context

Auto-generated by Codex Terminal. Run \`ha-context\` to refresh.
Last updated: ${timestamp}

## Codex Guidance

- Work in \`/config\` unless the user asks for another directory.
- Prefer the configured MCP server named \`home-assistant\` for Home Assistant reads and writes.
- Use Home Assistant native APIs and helpers where available.
- Avoid direct edits to Home Assistant internal \`.storage\` files unless the user explicitly asks and you have a backup.

## System

HEADER

    section_system_info >> "$tmp_file"

    cat >> "$tmp_file" << 'DIVIDER'

## Entities

DIVIDER

    section_entity_summary >> "$tmp_file"

    cat >> "$tmp_file" << 'DIVIDER'

## Installed Apps

DIVIDER

    section_apps >> "$tmp_file"

    cat >> "$tmp_file" << 'DIVIDER'

## Recent Errors

DIVIDER

    section_recent_errors >> "$tmp_file"

    cat >> "$tmp_file" << 'APIREF'

## API Access

The terminal has Supervisor and Home Assistant API access:

```bash
curl -H "Authorization: Bearer $SUPERVISOR_TOKEN" http://supervisor/core/info
curl -H "Authorization: Bearer $SUPERVISOR_TOKEN" http://supervisor/core/api/states
```

Available Home Assistant REST endpoints include `states`, `services`, `config`, `events`, `error_log`, and `history/period`.
APIREF

    chmod 644 "$tmp_file"
    mv "$tmp_file" "$OUTPUT_FILE"
}

main() {
    check_prerequisites
    echo "Generating Home Assistant context..." >&2
    generate_agents_md
    if [ "$FULL_MODE" = true ]; then
        echo "HA context (full) written to ${OUTPUT_FILE}" >&2
    else
        echo "HA context (medium) written to ${OUTPUT_FILE}" >&2
    fi
}

main "$@"
