name: Calibre-Web Automated
version: 4.0.6
slug: calibre_web_automated
url: https://github.com/crocodilestick/Calibre-Web-Automated
init: false
description: Calibre-Web Automated wrapped for Home Assistant OS.
webui: http://[HOST]:[PORT:8083]
stage: experimental
startup: application
boot: auto
panel_icon: mdi:book-open-page-variant
arch:
  - aarch64
  - amd64
ports:
  8083/tcp: 8083
ports_description:
  8083/tcp: Web interface and OPDS catalog
map:
  - addon_config:rw
  - share:rw
options:
  timezone: Europe/Zurich
  network_share_mode: false
  force_polling: false
  trusted_proxy_count: 1
  hardcover_token: ""
  disable_library_automount: false
schema:
  timezone: str
  network_share_mode: bool
  force_polling: bool
  trusted_proxy_count: int
  hardcover_token: str?
  disable_library_automount: bool
